<?php
require 'vendor/autoload.php';
$app = require 'bootstrap/app.php';
$app->make('Illuminate\Contracts\Console\Kernel')->bootstrap();

echo 'Auth session web: ' . config('auth.session.web') . PHP_EOL;
echo 'Auth guards web: ' . json_encode(config('auth.guards.web')) . PHP_EOL;

// Check the session key used by Laravel
$guard = auth()->guard('web');
echo 'Guard name: ' . $guard->getName() . PHP_EOL;

// The session key is generated by the guard
// It's typically: 'login_' . $guard->getName() . '_' . sha1($guard->getName() . config('auth.password'))
// But let's check what the actual key is in the working session
$s = DB::table('sessions')->where('user_id', 1)->orderBy('last_activity', 'desc')->first();
if ($s) {
    $payload = json_decode($s->payload, true);
    echo "Working session payload keys: " . implode(', ', array_keys($payload)) . PHP_EOL;
    foreach($payload as $k => $v) {
        if (str_starts_with($k, 'login_')) {
            echo "Found login key: $k = $v" . PHP_EOL;
        }
    }
}